# ************************************************************************* #
#                                                                           #
#                                                      :::      ::::::::    #
#  Vocabulary.py                                     :+:      :+:    :+:    #
#                                                  +:+ +:+         +:+      #
#  By: roandrie <roandrie@student.42lehavre.fr   +#+  +:+       +#+         #
#                                              +#+#+#+#+#+   +#+            #
#  Created: 2026/04/13 11:41:33 by roandrie        #+#    #+#               #
#  Updated: 2026/04/22 22:25:20 by roandrie        ###   ########.fr        #
#                                                                           #
# ************************************************************************* #
"""
Vocabulary management module.

This module is responsible for loading the LLM's vocabulary map and providing
utility functions for constrained decoding. It handles the translation between
string tokens and their corresponding integer IDs used by the model's tokenizer
"""

from typing import Any, Dict, List

import json

from pydantic import BaseModel, Field, PrivateAttr

from src.utils import print_log


class Vocabulary(BaseModel):
    """
    Manager for the LLM's tokenizer vocabulary.

    Attributes:
        path_file (str): The absolute or relative path to the JSON
            vocabulary file.
        debug (bool): Flag to enable detailed debug logging.
    """

    path_file: str = Field(
        description="Path to the vocabulary file"
    )
    debug: bool = Field(
        description="The state of the debug mode",
        default=False
    )

    _vocab_path: str = PrivateAttr()
    _vocab_data: Dict[str, int] = PrivateAttr()

    def model_post_init(self, context: Any) -> None:
        """Initialize the private vocabulary state."""
        self._load_vocab(self.path_file)

        return super().model_post_init(context)

    def get_id_to_token_vocab(self) -> Dict[int, str]:
        """
        Generate a reverse mapping of the vocabulary.

        Returns:
            Dict[int, str]: A dictionary mapping token integer IDs back
            to their string representations. Useful for decoding outputs.
        """
        reverse_vocab: dict[int, str] = {}

        # Loop throught each item to inverse the key and the value
        for key, value in self._vocab_data.items():
            reverse_vocab[value] = key

        return reverse_vocab

    def get_valid_token_ids(self, current_output: str,
                            valid_names: List[str]) -> List[int]:
        """
        Determine the valid next token IDs for constrained decoding.

        Evaluates all available tokens in the vocabulary to identify which
        ones can be legally appended to the current output string while
        remaining a valid prefix for at least one target string.

        Args:
            current_output (str): The string generated by the model so far.
            valid_names (List[str]): A list of all allowed complete target
                strings (e.g., valid function names).

        Returns:
            List[int]: A list of valid token IDs that can safely be generated
            next.
        """
        valid_id: list[int] = []
        reverse_vocab: dict[int, str] = self.get_id_to_token_vocab()

        # Iterate through every single token available in the model's
        # vocabulary
        for key, item in reverse_vocab.items():
            # Simulate what the output would look like if this token was chosen
            candidat = current_output + item

            # Verify if this simulated output matches the beginning of any
            # allowed target string
            for name in valid_names:

                # If it is a valid prefix, save the token ID
                if name.startswith(candidat):
                    valid_id.append(key)
                    break

        return valid_id

    def _load_vocab(self, path: str) -> None:
        """
        Load the vocabulary mapping from the specified JSON file.

        Args:
            path (str): The file path to load.

        Raises:
            ValueError: If the file cannot be found, opened, or parsed.
        """
        try:
            # Open the vocab file
            with open(path, 'r', encoding='utf-8') as f:
                data = json.load(f)

            if "model" in data and "vocab" in data["model"]:
                vocab = data["model"]["vocab"]
            else:
                vocab = data

            if self.debug:
                print_log(
                    "[green]"
                    "✅ Vocabulary loaded!"
                    "[/green]"
                )

            # Save the loaded vocab json file
            self._vocab_data = vocab

        except Exception as e:
            raise ValueError(f"error while loading vocab path {e}")
